version: '3.9'

services:

  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ads_website